bundler_args: --without development
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
language: ruby
rvm:
  - 1.9.3
  - 2.1.2
  - 2.1.3
  - jruby-19mode
  - jruby-head
  - ruby-head
jdk:
  - openjdk7
  - oraclejdk7
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true
sudo: false
